/*School Ranking Analysis.
DESCRIPTION
Consider an institution that wants to store the students’ details and their marks records to track their progress. The database would contain the students’ information, marks of the students with the rank that can be viewed, updated, and evaluated for the performance evaluation.
Objective:
The design of the database helps to easily retrieve thousands of student records.*/

/*Tasks performed:*/

/*Query to create a students table with appropriate data types 
	for student id, student first name, student last name, class, and age 
    where the student last name, student first name, and student id should be a NOT NULL constraint, 
    and the student id should be in a primary key.*/
    
CREATE DATABASE STUDENT;

CREATE TABLE IF NOT EXISTS
	STUDENT.STU_DETAIL (
		STU_ID VARCHAR(4) NOT NULL,
        STU_FIRST_NAME VARCHAR(100) NOT NULL,
        STU_LAST_NAME VARCHAR(100) NOT NULL,
        STU_CLASS VARCHAR(10),
        AGE INT
        ) ENGINE = InnoDB;
        
DESCRIBE STUDENT.STU_DETAIL;

/*Query to create a marksheet table that includes score, year, ranking, class, and student id.*/

CREATE TABLE IF NOT EXISTS
	STUDENT.MARKSHEET (
		SCORE INT NOT NULL,
        PASS_YEAR INT NOT NULL,
        RANKING INT NOT NULL,
        STU_CLASS VARCHAR(10),
        STU_ID VARCHAR(4) NOT NULL
        ) ENGINE = InnoDB;

DESCRIBE STUDENT.MARKSHEET;

/*Query to insert values in students*/
INSERT INTO STUDENT.STU_DETAIL (STU_ID,STU_FIRST_NAME,STU_LAST_NAME,STU_CLASS,AGE)
	VALUES('ST11','YAMUNA','MURUGESAN','GRADE 3',8);
    
INSERT INTO STUDENT.STU_DETAIL (STU_ID,STU_FIRST_NAME,STU_LAST_NAME,STU_CLASS,AGE)
	VALUES('ST12','ANANYA','JEEVAN','GRADE 3',8);
    
INSERT INTO STUDENT.STU_DETAIL (STU_ID,STU_FIRST_NAME,STU_LAST_NAME,STU_CLASS,AGE)
	VALUES('ST13','PRAGANYA','JEEVAN','GRADE 3',8);
    
INSERT INTO STUDENT.STU_DETAIL (STU_ID,STU_FIRST_NAME,STU_LAST_NAME,STU_CLASS,AGE)
	VALUES('ST14','JEEVAN','RAVI','GRADE 3',8);
    
INSERT INTO STUDENT.STU_DETAIL (STU_ID,STU_FIRST_NAME,STU_LAST_NAME,STU_CLASS,AGE)
	VALUES('ST15','ESWARI','RAVI','GRADE 3',8);
    
INSERT INTO STUDENT.STU_DETAIL (STU_ID,STU_FIRST_NAME,STU_LAST_NAME,STU_CLASS,AGE)
	VALUES('ST16','MURUGESESAN','MUTHU','GRADE 5',10);

INSERT INTO STUDENT.STU_DETAIL (STU_ID,STU_FIRST_NAME,STU_LAST_NAME,STU_CLASS,AGE)
	VALUES('ST17','JANAKI','MUTHU','GRADE 5',10);
    
INSERT INTO STUDENT.STU_DETAIL (STU_ID,STU_FIRST_NAME,STU_LAST_NAME,STU_CLASS,AGE)
	VALUES('ST18','PRAVEEN','MUTHU','GRADE 5',10);

INSERT INTO STUDENT.STU_DETAIL (STU_ID,STU_FIRST_NAME,STU_LAST_NAME,STU_CLASS,AGE)
	VALUES('ST19','VIJI','PRAVEEN','GRADE 5',10);
    
INSERT INTO STUDENT.STU_DETAIL (STU_ID,STU_FIRST_NAME,STU_LAST_NAME,STU_CLASS,AGE)
	VALUES('ST20','PRAVISH','PRAVEEN','GRADE 5',10);
    
INSERT INTO STUDENT.STU_DETAIL (STU_ID,STU_FIRST_NAME,STU_LAST_NAME,STU_CLASS,AGE)
	VALUES('ST21','PRAVISH','KUMAR','GRADE 5',10);
    
INSERT INTO STUDENT.STU_DETAIL (STU_ID,STU_FIRST_NAME,STU_LAST_NAME,STU_CLASS,AGE)
	VALUES('ST22','RAJU','KUMAR','GRADE 5',10);
    
INSERT INTO STUDENT.STU_DETAIL (STU_ID,STU_FIRST_NAME,STU_LAST_NAME,STU_CLASS,AGE)
	VALUES('ST23','KESAVA','KUMAR','GRADE 3',8);
    
INSERT INTO STUDENT.STU_DETAIL (STU_ID,STU_FIRST_NAME,STU_LAST_NAME,STU_CLASS,AGE)
	VALUES('ST24','PRAVISH','KUMAR','COL 1',18);
    
INSERT INTO STUDENT.STU_DETAIL (STU_ID,STU_FIRST_NAME,STU_LAST_NAME,STU_CLASS,AGE)
	VALUES('ST25','RAJU','KUMAR','COL 1',16);
    
INSERT INTO STUDENT.STU_DETAIL (STU_ID,STU_FIRST_NAME,STU_LAST_NAME,STU_CLASS,AGE)
	VALUES('ST26','KESAVA','KUMAR','COL 1',20);
    
SELECT * FROM STUDENT.STU_DETAIL;
    
/*Query to insert values in marksheet tables.*/

INSERT INTO STUDENT.MARKSHEET (SCORE,PASS_YEAR,RANKING,STU_CLASS,STU_ID)
	VALUES('79','2000','5','GRADE 5','ST16');
    
INSERT INTO STUDENT.MARKSHEET (SCORE,PASS_YEAR,RANKING,STU_CLASS,STU_ID)
	VALUES('65','2000','6','GRADE 5','ST17');
    
INSERT INTO STUDENT.MARKSHEET (SCORE,PASS_YEAR,RANKING,STU_CLASS,STU_ID)
	VALUES('77','2000','5','GRADE 5','ST18');
    
INSERT INTO STUDENT.MARKSHEET (SCORE,PASS_YEAR,RANKING,STU_CLASS,STU_ID)
	VALUES('79','2000','5','GRADE 3','ST11');
    
INSERT INTO STUDENT.MARKSHEET (SCORE,PASS_YEAR,RANKING,STU_CLASS,STU_ID)
	VALUES('89','2000','5','GRADE 3','ST14');
    
INSERT INTO STUDENT.MARKSHEET (SCORE,PASS_YEAR,RANKING,STU_CLASS,STU_ID)
	VALUES('800','2000','3','GRADE 3','ST14');
    
INSERT INTO STUDENT.MARKSHEET (SCORE,PASS_YEAR,RANKING,STU_CLASS,STU_ID)
	VALUES('850','2000','3','GRADE 3','ST11');
    
INSERT INTO STUDENT.MARKSHEET (SCORE,PASS_YEAR,RANKING,STU_CLASS,STU_ID)
	VALUES('1000','2000','1','GRADE 3','ST12');
    
INSERT INTO STUDENT.MARKSHEET (SCORE,PASS_YEAR,RANKING,STU_CLASS,STU_ID)
	VALUES('1020','2000','1','GRADE 3','ST13');
    
INSERT INTO STUDENT.MARKSHEET (SCORE,PASS_YEAR,RANKING,STU_CLASS,STU_ID)
	VALUES('955','2000','5','GRADE 3','ST14');
    
SELECT * FROM STUDENT.MARKSHEET;

/*Query to display student id and student first name from the student table 
	if the age is greater than or equal to 16 
    and the student's last name is Kumar.*/

SELECT STU_ID,STU_FIRST_NAME FROM STUDENT.STU_DETAIL
	WHERE AGE >= 16 AND STU_LAST_NAME = 'KUMAR';    

/*Query to display all the details from the marksheet table if the score is between 800 and 1000.*/

SELECT * FROM STUDENT.MARKSHEET
	WHERE SCORE BETWEEN 800 AND 1000; 

/*Query to display the marksheet details from the marksheet table 
	by adding 5 to the score and by naming the column as new score.*/
    
ALTER TABLE STUDENT.MARKSHEET 
	ADD NEW_SCORE INT
    GENERATED ALWAYS AS (SCORE+5);
    
SELECT * FROM STUDENT.MARKSHEET;

/*Query to display the marksheet table in descending order of the  score.*/

SELECT * FROM STUDENT.MARKSHEET
	ORDER BY SCORE DESC;

/*Query to display details of the students whose first name starts with a.*/

SELECT * FROM STUDENT.STU_DETAIL
	WHERE STU_FIRST_NAME LIKE "A%";
